project:
  type: website
  output-dir: docs

website:
  title: "Datos Masivos"
  sidebar:
    background: primary
    # logo: "images/logo.png"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/yabellini/gestiondedatos
        text: GitHub
    style: docked
    contents:
      - href: index.qmd
        text: Home
      - href: schedule.qmd
        text: Schedule
      - href: clase1.qmd
        text: Clase 1 - Introducción
      - href: clase2.qmd
        text: Clase 2 - Tipos de Datos
      - href: clase3.qmd
        text: Clase 3 - NOSQL y Text Mining
      - href: clase4.qmd
        text: Clase 4 - Scrapping y Limpieza de datos
      - href: clase5.qmd
        text: Clase 5 - Text Mining en R
      - href: clase6.qmd
        text: Clase 6 - Geotecnologias
      - href: clase7.qmd
        text: Clase 7 -
      - href: clase8.qmd
        text: Clase 8 -
      - href: clase9.qmd
        text: Clase 9 -
      - href: clase10.qmd
        text: Clase 10 -
      - href: OpenRefine.qmd
        text: Guía de OpenRefine
      - href: Geocoding.qmd
        text: Guía de Información Georeferenciada
      - href: libros.qmd
        text: Libros sugeridos

format:
  html:
    theme: sandstone
    # css: styles.css
    toc: true

execute:
  freeze: auto

